# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box     = "precise64_docker"
  config.vm.box_url = "http://bit.ly/vagrant-docker-precise"

  config.vm.provider :docker do |docker|
  end
  config.vm.provision :puppet do |puppet|
    puppet.module_path = "./manifests/modules"
    puppet.facter = {
      "is_vagrant" => true
    }
  end
end
